### PR TITLE
Onboarding Docker

### PR DESCRIPTION
**Pull request by guimatheus92**
### Description

This project can use and be leveraged by Docker to manage the build environment. Using Docker ensures that the build process is consistent and isolated from the host machine, avoiding issues related to different operating systems and environments.

Using Docker Compose is a great way to manage your Docker configurations and run commands in a platform-independent way. Also, this approach makes it easier to manage your Docker setup and avoids platform-specific command issues. You can use the same docker-compose.yml file across different environments (Windows, macOS, Linux) without needing to modify the volume mount command.

### How Has This Been Tested?

Run the command below that you will be able to build the project just fine:

- `docker-compose run --rm plugin-builder build`

In the `build` keyword, it can be replaced and used any command specified in this list [How to contribute](https://github.com/shmuelzon/home-assistant-floor-plan/blob/master/CONTRIBUTING.md#on-nix-systems)

### Checklist

* [X] I have tested and built the changes locally and they work as expected
* [ ] I have added relevant documentation or updated existing documentation
* [X] My changes generate no new warnings

### Screenshots (if applicable)

Project cloned:

image

After project built from Docker:

image

### Additional Context

**I will add relevant documentation in another PR.**

### Log

```
[+] Creating 1/0
 ✔ Network home-assistant-floor-plan_default  Created                                                                                                                                              0.0s 
mkdir -p build/com/shmuelzon/HomeAssistantFloorPlan/
envsubst < src/com/shmuelzon/HomeAssistantFloorPlan/ApplicationPlugin.properties > build/com/shmuelzon/HomeAssistantFloorPlan/ApplicationPlugin.properties
Downloading SweetHome3D-7.4.jar
dl/SweetHome3D-7.4.jar                            100%[=============================================================================================================>]  45.24M  13.4MB/s    in 3.4s    
Downloading j3dcore.jar
dl/j3dcore.jar                                    100%[=============================================================================================================>]   2.71M  2.31MB/s    in 1.2s    
Downloading vecmath.jar
dl/vecmath.jar                                    100%[=============================================================================================================>] 306.99K   482KB/s    in 0.6s    
javac -classpath "dl/*:src" -target 1.5 -source 1.5 -d build src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -classpath "dl/*:src" -target 1.5 -source 1.5 -d build src/com/shmuelzon/HomeAssistantFloorPlan/Panel.java
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -classpath "dl/*:src" -target 1.5 -source 1.5 -d build src/com/shmuelzon/HomeAssistantFloorPlan/Plugin.java
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
jar -cf HomeAssistantFloorPlanPlugin-45146f0.sh3p -C build .
```

### CODE REVIEW

**Comment by shmuelzon** [comment]
This seems overly complicated to me... Why build a special image with the plugin source files just to build them?
In other projects, I usually use existing Docker images and build with the source directory mounted inside and all the outputs are saved their as well making Docker just a wrapper to the build commands.

Check out https://github.com/shmuelzon/home-assistant-floor-plan/pull/61 and let me know what you think.
Seems to work fine for me for building both with and without Docker available. One does need `make` to exist on the machine but I'm fine with that requirement.

**Comment by guimatheus92** [comment]
Thanks for checking this PR. I also use Docker images in other projects as you said, but I have also seen users having challenges in the same projects to emulate or run a given application. But in this project specifically, it might be "confuse" to build an image just to build the application and generate the necessary file, but in this case it might help others users to Contribute to this amazing project by following `Contributing.md` and also to unblock any problems and be isolated from the host machine, avoiding issues related to different operating systems and environments.

I don't know, but I think that in this case having Docker would not do any "harm", regardless of whether it adds as much as it could in other projects as we discussed.

**Comment by shmuelzon** [comment]
I'm not (too much) against using Docker to build this project, i just took a different approach as you. I would be happy to hear if it works for you too.

**Comment by guimatheus92** [comment]
> I'm not (too much) against using Docker to build this project, i just took a different approach as you. I would be happy to hear if it works for you too.

Sure! Do you mind sharing a step by step how should the new changes impact the build process? I mean, how does the new change works?

**Comment by shmuelzon** [comment]
You build the same as before, with `make`. Behind the scenes (and if you have Docker installed), it'll run Docker with en Eclipse image of Java 8 and compile everything. I also opted to prettify the build process to hide the commands used as they are pretty long with Docker in the mix. You can compile with `make V=1` if you want the verbose output like it was before

**Comment by guimatheus92** [comment]
I see, it works. It's a nice solution as well. But I think it doesn't have the greatest feature and scape which user can isolate from the host machine, so user can contribute to this project in any OS available, and doesn't need to worry about `Makefile` at all. That's my point of view.

I will leave the decision with you now. Feel free to reject if you want, but I strongly support this isolation environment and worrying about improving the features of the plugin.

**Comment by shmuelzon** [comment]
I tried using your branch here but there are several issues that I see with the way it's currently implemented.
* It runs everything as root so all of the download files, build files and plugin all belong to root
* Why do we need to build the project as a part of the Docker image? Shouldn't it be built using the Docker image and rebuilt when the developer makes a change and wants to build again?
* The project files are copied to the Docker image but you use a volume when running it anyway. Why do you need the copy (and the `.dockerignore` file)?
* I couldn't get the `make test` to run, i.e., start SH3D with the Docker, does that actually work for you?
* The openjdk Docker image is deprecated

Even with the above fixed, I'm still not sure about this path, so please don't invest any time on it just yet on my behalf

**Pull request closed without merging**
