### PR TITLE
Add other entities to Panel

### PR DESCRIPTION
**Pull request by guimatheus92**
### Description

This changes is to add other entities that are lights to another tab, so that we can change settings for them as well.
I have some use cases to change how this entities should be shown in HA and not with fixed settings as of now.

This is to solve #63.

### How Has This Been Tested?

Check screenshot below.

### Checklist

* [X] I have tested and built the changes locally and they work as expected
* [X] I have added relevant documentation or updated existing documentation
* [X] My changes generate no new warnings

### Screenshots (if applicable)

image

### CODE REVIEW

**Comment by guimatheus92** [comment]
@shmuelzon Can you give a little help please? I wasn't able to generate all remaining entities (ignoring lights) and list them in the second tab, only a few. For some reason, not all ´switch.xxx´ is being listed, and I wasn't able to understand/debug this. I will share my own project so you can take a look if helps. Thanks!

Project (one drive link): https://1drv.ms/u/s!AgnBdF_BgESzjqthR-JIJn8Op8u63g?e=lcM8nr
Note: I wasn't able to attach my file here because it was greater than 25MB even if in `.zip`, `.7z` format.

**Comment by shmuelzon** [comment]
Yes, I'll handle it. I want to do it a bit differently anyway...

**Comment by shmuelzon** [comment]
Hey, thanks for this. I implemented it is a part of https://github.com/shmuelzon/home-assistant-floor-plan/pull/79. I opted for a side-by-side view instead of tabs.

**Comment by guimatheus92** [comment]
> Hey, thanks for this. I implemented it is a part of #79. I opted for a side-by-side view instead of tabs.

Were you able to use my project to test the results? There are some entities that is not showing to me still. That's the bug I have mentioned on my last response, I have other `switch.xxx` entities, but it's only showing one:

image

**Comment by shmuelzon** [comment]
I see those switches are on a different level then the rest. Either move them to same level as the rest or, alternatively, select "Display all levels" in the 3D view.

**Pull request closed without merging**
