### PR TITLE
Allow stopping rendering thread

### PR DESCRIPTION
**Pull request by guimatheus92**
Now we are able to cancel the render thread and restore lights power to initial state if cancel is set to true.
This was also mention in the issue #33.

You can see the `Close` button is now enabled:

image

And only certain images were generated:

image

### CODE REVIEW

**Comment by shmuelzon** [comment]
Hey, as far as I can tell, this doesn't stop the currently rendered image so that will continue. We should be able to stop it by calling `photoRenderer.stop()` (but we'll need to move that variable to be a part of the class instead of a local variable in `renderScene()`. Another option is to stop the renderer thread altogether. It seems like that's what [SH3D](https://sourceforge.net/p/sweethome3d/code/HEAD/tree/trunk/SweetHome3D/src/com/eteks/sweethome3d/swing/PhotosPanel.java#l764) does 

If we don't stop the thread, we can also think about raising an exception or something instead of relying on the `isCanceled` everywhere. Maybe see if the image was actually rendered or we can set `photoRenderer` to `null` and use that as an indicator.

**Comment by shmuelzon** [comment]
It'll also be nicer to replace the start button with a stop button, like SH3D does

**Comment by guimatheus92** [comment]
> It'll also be nicer to replace the start button with a stop button, like SH3D does

But in this case what would be the difference between `Stop` and `Close`? I tested on SH3D and they do the same things looks like. Should I keep only one button `Start` in this case, and replace to `Stop` once render starts?

**Comment by shmuelzon** [comment]
> But in this case what would be the difference between Stop and Close? I tested on SH3D and they do the same things looks like. Should I keep only one button Start in this case, and replace to Stop once render starts?

This is what SH3D do with their image render. The close button is always enabled and will both stop the current render and close the window. The start button turns into stop and just halts the renderer. It keeps the window open letting the user change a configuration setting and start again.

> I am working on this one, it was stopping the thread with my code but not using the class from SH3D. I am doing the modifications.

I add the attached changes to make the currently-rendered image to stop as well.
I was hoping that the call to `renderExecutor.shutdownNow()` what stop the thread and not continue to the next image but that doesn't seem to be the case. I don't like the `isCanceled` conditions all over the place. I would rather we raise an exception or something to stop everything. Since the controller isn't aware of the fact that's it running in a thread, I don't know what it needs to do to know that something stopped its execution. If it could detect and raise an `InterruptedException` that would be best.

[stop.patch](https://github.com/user-attachments/files/16311512/stop.patch)

**Comment by shmuelzon** [comment]
OK, I figured it out and added the stop button. Merging now

**Comment by guimatheus92** [comment]
> OK, I figured it out and added the stop button. Merging now

Awesome, I am glad you help me out. Thanks!

**Pull request merged**
