### PR TITLE
Define settings per entity and save persistently

### PR DESCRIPTION
**Pull request by guimatheus92**
### Description

1. **Entity Options Panel Update:**
   - A new `EntityOptionsPanel` was created to provide a user-friendly interface for configuring entities. This panel allows users to select specific settings for each entity, such as state options, tap actions, and always-on status. 
   - The panel dynamically retrieves and displays the current settings for each entity, offering a seamless way to make adjustments (following the Settings save from #57.

2. **State Options Mapping:**
   - A mapping for state options (`state-badge`, `state-icon`, `state-label`) was implemented, enabling users to choose from predefined state representations. This ensures that the selected state type is correctly applied to the entity.

3. **Tap Action Configuration:**
   - A new feature was added to configure `tap_action` for entities, allowing users to define what action should occur when the entity is tapped. Available options include `none`, `toggle`, and `more-info`, with `toggle` set as the default.

4. **Always On Configuration:**
   - Added a new property called Always On, allowing users to specify if a light should remain on at all times during the render process, this was requested on #55. 

### How Has This Been Tested?

Using a SH3D project I was able to click on a given entity, modify the new settings for this entity and apply.
After generation of YAML file, I could see that some properties were updated for that entity only, as example below:

image

I have also added a new property called `Always On`, so that user can choose if that light needs to be always on, which means that it won't be set power equals 0 during the scene preparation before creating the rendering. So that, every render that light will keep on as defined in SH3D, example:

image

image

### Checklist

* [X] I have tested and built the changes locally and they work as expected
* [X] I have added relevant documentation or updated existing documentation
* [X] My changes generate no new warnings

### Additional Context

I have followed the suggestion from @shmuelzon to create a new panel rather than increasing the tree. We might, later on, add properties to entities that be more complex. I chose not to use a tree view in the second panel, `EntityOptionsPanel.java`, because a simpler and more focused user interface was needed. `JTree` is generally used for displaying hierarchical data, which isn't necessary for configuring individual entity settings. Instead, `EntityOptionsPanel` is designed to be straightforward and user-friendly, allowing users to easily adjust specific options like state options, tap actions, and always-on status directly.

### CODE REVIEW

**Comment by guimatheus92** [comment]
@shmuelzon JFYI: I will add more properties such as X and Y location of an entity in future PRs, as we have been doing.

**Comment by shmuelzon** [comment]
I've also noticed that when double clicking on the tree, some things move around. Any idea why?
offset

**Comment by shmuelzon** [comment]
Sure thing, let me know when you're done and I'll take over from there so we don't work on the same things

**Comment by guimatheus92** [comment]
> Sure thing, let me know when you're done and I'll take over from there so we don't work on the same things

I have pushed some changes as you suggested, the unresolved comments is what I have not done. I also left some reply to some of your comments so you can validate it.

After I made some changes to `EntityOptionsPanel.java` to have the same implementation as `Panel.java`, the Apply button stopped working and I couldn't figure out why. Can you help on this one please? Thanks!

**Review by shmuelzon — APPROVED** [review]

**Comment by guimatheus92** [comment]
@shmuelzon thanks for merging! As a UI perspective, can we keep cursor in the node tree? The current doesn't have any clue/tip that entity is configurable or not.

**Comment by shmuelzon** [comment]
It bugged me that the cursor was set for the entire tree, as if it was all clickable (which it technically is, but that's weird too). I wanted to make only the nodes clickable and so only they should have a different cursor but that seemed too complex for me to complete right now and I didn't want to keep this feature waiting so I decided to merge it as is and handle it later

**Pull request merged**
